package com.fr.chain.property.db.mapper;

import com.fr.chain.db.iface.StaticTableDaoSupport;
import com.fr.chain.property.db.entity.ProductDigit;
import com.fr.chain.property.db.entity.ProductDigitExample;
import com.fr.chain.property.db.entity.ProductDigitKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ProductDigitMapper extends StaticTableDaoSupport<ProductDigit, ProductDigitExample, ProductDigitKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_DIGIT
     *
     * @mbggenerated Fri Feb 24 10:10:34 CST 2017
     */
    @SelectProvider(type=ProductDigitSqlProvider.class, method="countByExample")
    int countByExample(ProductDigitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_DIGIT
     *
     * @mbggenerated Fri Feb 24 10:10:34 CST 2017
     */
    @DeleteProvider(type=ProductDigitSqlProvider.class, method="deleteByExample")
    int deleteByExample(ProductDigitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_DIGIT
     *
     * @mbggenerated Fri Feb 24 10:10:34 CST 2017
     */
    @Delete({
        "delete from PRODUCT_DIGIT",
        "where PRODUCT_ID = #{productId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(ProductDigitKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_DIGIT
     *
     * @mbggenerated Fri Feb 24 10:10:34 CST 2017
     */
    @Insert({
        "insert into PRODUCT_DIGIT (PRODUCT_ID, MERCHANT_ID, ",
        "APP_ID, PRODUCT_DESC, ",
        "CHAIN_TYPE, PROPERTY_TYPE, ",
        "PROPERTY_CODE, ORIGIN_OPENID, ",
        "SIGN_TYPE, PROPERTY_NAME, ",
        "UNIT, MIN_COUNT, ",
        "URL, DESCRIPTION, ",
        "CREATE_TIME, UPDATE_TIME, ",
        "STATUS)",
        "values (#{productId,jdbcType=VARCHAR}, #{merchantId,jdbcType=VARCHAR}, ",
        "#{appId,jdbcType=VARCHAR}, #{productDesc,jdbcType=VARCHAR}, ",
        "#{chainType,jdbcType=INTEGER}, #{propertyType,jdbcType=INTEGER}, ",
        "#{propertyCode,jdbcType=VARCHAR}, #{originOpenid,jdbcType=VARCHAR}, ",
        "#{signType,jdbcType=VARCHAR}, #{propertyName,jdbcType=VARCHAR}, ",
        "#{unit,jdbcType=VARCHAR}, #{minCount,jdbcType=VARCHAR}, ",
        "#{url,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{status,jdbcType=INTEGER})"
    })
    int insert(ProductDigit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_DIGIT
     *
     * @mbggenerated Fri Feb 24 10:10:34 CST 2017
     */
    @InsertProvider(type=ProductDigitSqlProvider.class, method="insertSelective")
    int insertSelective(ProductDigit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_DIGIT
     *
     * @mbggenerated Fri Feb 24 10:10:34 CST 2017
     */
    @SelectProvider(type=ProductDigitSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="PRODUCT_ID", property="productId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="MERCHANT_ID", property="merchantId", jdbcType=JdbcType.VARCHAR),
        @Result(column="APP_ID", property="appId", jdbcType=JdbcType.VARCHAR),
        @Result(column="PRODUCT_DESC", property="productDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="CHAIN_TYPE", property="chainType", jdbcType=JdbcType.INTEGER),
        @Result(column="PROPERTY_TYPE", property="propertyType", jdbcType=JdbcType.INTEGER),
        @Result(column="PROPERTY_CODE", property="propertyCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORIGIN_OPENID", property="originOpenid", jdbcType=JdbcType.VARCHAR),
        @Result(column="SIGN_TYPE", property="signType", jdbcType=JdbcType.VARCHAR),
        @Result(column="PROPERTY_NAME", property="propertyName", jdbcType=JdbcType.VARCHAR),
        @Result(column="UNIT", property="unit", jdbcType=JdbcType.VARCHAR),
        @Result(column="MIN_COUNT", property="minCount", jdbcType=JdbcType.VARCHAR),
        @Result(column="URL", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="DESCRIPTION", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_TIME", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="STATUS", property="status", jdbcType=JdbcType.INTEGER)
    })
    List<ProductDigit> selectByExample(ProductDigitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_DIGIT
     *
     * @mbggenerated Fri Feb 24 10:10:34 CST 2017
     */
    @Select({
        "select",
        "PRODUCT_ID, MERCHANT_ID, APP_ID, PRODUCT_DESC, CHAIN_TYPE, PROPERTY_TYPE, PROPERTY_CODE, ",
        "ORIGIN_OPENID, SIGN_TYPE, PROPERTY_NAME, UNIT, MIN_COUNT, URL, DESCRIPTION, ",
        "CREATE_TIME, UPDATE_TIME, STATUS",
        "from PRODUCT_DIGIT",
        "where PRODUCT_ID = #{productId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="PRODUCT_ID", property="productId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="MERCHANT_ID", property="merchantId", jdbcType=JdbcType.VARCHAR),
        @Result(column="APP_ID", property="appId", jdbcType=JdbcType.VARCHAR),
        @Result(column="PRODUCT_DESC", property="productDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="CHAIN_TYPE", property="chainType", jdbcType=JdbcType.INTEGER),
        @Result(column="PROPERTY_TYPE", property="propertyType", jdbcType=JdbcType.INTEGER),
        @Result(column="PROPERTY_CODE", property="propertyCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORIGIN_OPENID", property="originOpenid", jdbcType=JdbcType.VARCHAR),
        @Result(column="SIGN_TYPE", property="signType", jdbcType=JdbcType.VARCHAR),
        @Result(column="PROPERTY_NAME", property="propertyName", jdbcType=JdbcType.VARCHAR),
        @Result(column="UNIT", property="unit", jdbcType=JdbcType.VARCHAR),
        @Result(column="MIN_COUNT", property="minCount", jdbcType=JdbcType.VARCHAR),
        @Result(column="URL", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="DESCRIPTION", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_TIME", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="STATUS", property="status", jdbcType=JdbcType.INTEGER)
    })
    ProductDigit selectByPrimaryKey(ProductDigitKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_DIGIT
     *
     * @mbggenerated Fri Feb 24 10:10:34 CST 2017
     */
    @UpdateProvider(type=ProductDigitSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ProductDigit record, @Param("example") ProductDigitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_DIGIT
     *
     * @mbggenerated Fri Feb 24 10:10:34 CST 2017
     */
    @UpdateProvider(type=ProductDigitSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ProductDigit record, @Param("example") ProductDigitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_DIGIT
     *
     * @mbggenerated Fri Feb 24 10:10:34 CST 2017
     */
    @UpdateProvider(type=ProductDigitSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ProductDigit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_DIGIT
     *
     * @mbggenerated Fri Feb 24 10:10:34 CST 2017
     */
    @Update({
        "update PRODUCT_DIGIT",
        "set MERCHANT_ID = #{merchantId,jdbcType=VARCHAR},",
          "APP_ID = #{appId,jdbcType=VARCHAR},",
          "PRODUCT_DESC = #{productDesc,jdbcType=VARCHAR},",
          "CHAIN_TYPE = #{chainType,jdbcType=INTEGER},",
          "PROPERTY_TYPE = #{propertyType,jdbcType=INTEGER},",
          "PROPERTY_CODE = #{propertyCode,jdbcType=VARCHAR},",
          "ORIGIN_OPENID = #{originOpenid,jdbcType=VARCHAR},",
          "SIGN_TYPE = #{signType,jdbcType=VARCHAR},",
          "PROPERTY_NAME = #{propertyName,jdbcType=VARCHAR},",
          "UNIT = #{unit,jdbcType=VARCHAR},",
          "MIN_COUNT = #{minCount,jdbcType=VARCHAR},",
          "URL = #{url,jdbcType=VARCHAR},",
          "DESCRIPTION = #{description,jdbcType=VARCHAR},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
          "UPDATE_TIME = #{updateTime,jdbcType=TIMESTAMP},",
          "STATUS = #{status,jdbcType=INTEGER}",
        "where PRODUCT_ID = #{productId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(ProductDigit record);
}