package com.fr.chain.property.db.entity;

import com.fr.chain.utils.CustomDateSerializer;
import com.fr.chain.web.bean.Tab;
import java.util.Date;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="PRODUCT_INFO")
public class ProductInfo extends ProductInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO.MERCHANT_ID
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    private String merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO.APP_ID
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO.PRODUCT_DESC
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    private String productDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO.PROPERTY_TYPE
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    private Integer propertyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO.PROPERTY_CODE
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    private Integer propertyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO.ORIGIN_OPENID
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    private String originOpenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO.SIGN_TYPE
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    private String signType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO.PROPERTY_NAME
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    private String propertyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO.UNIT
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO.MIN_COUNT
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    private String minCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO.URL
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO.DESCRIPTION
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO.CREATE_TIME
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO.UPDATE_TIME
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO.STATUS
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_INFO.MERCHANT_ID
     *
     * @return the value of PRODUCT_INFO.MERCHANT_ID
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_INFO.MERCHANT_ID
     *
     * @param merchantId the value for PRODUCT_INFO.MERCHANT_ID
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_INFO.APP_ID
     *
     * @return the value of PRODUCT_INFO.APP_ID
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_INFO.APP_ID
     *
     * @param appId the value for PRODUCT_INFO.APP_ID
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_INFO.PRODUCT_DESC
     *
     * @return the value of PRODUCT_INFO.PRODUCT_DESC
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    public String getProductDesc() {
        return productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_INFO.PRODUCT_DESC
     *
     * @param productDesc the value for PRODUCT_INFO.PRODUCT_DESC
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_INFO.PROPERTY_TYPE
     *
     * @return the value of PRODUCT_INFO.PROPERTY_TYPE
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    public Integer getPropertyType() {
        return propertyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_INFO.PROPERTY_TYPE
     *
     * @param propertyType the value for PRODUCT_INFO.PROPERTY_TYPE
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    public void setPropertyType(Integer propertyType) {
        this.propertyType = propertyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_INFO.PROPERTY_CODE
     *
     * @return the value of PRODUCT_INFO.PROPERTY_CODE
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    public Integer getPropertyCode() {
        return propertyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_INFO.PROPERTY_CODE
     *
     * @param propertyCode the value for PRODUCT_INFO.PROPERTY_CODE
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    public void setPropertyCode(Integer propertyCode) {
        this.propertyCode = propertyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_INFO.ORIGIN_OPENID
     *
     * @return the value of PRODUCT_INFO.ORIGIN_OPENID
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    public String getOriginOpenid() {
        return originOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_INFO.ORIGIN_OPENID
     *
     * @param originOpenid the value for PRODUCT_INFO.ORIGIN_OPENID
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    public void setOriginOpenid(String originOpenid) {
        this.originOpenid = originOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_INFO.SIGN_TYPE
     *
     * @return the value of PRODUCT_INFO.SIGN_TYPE
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    public String getSignType() {
        return signType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_INFO.SIGN_TYPE
     *
     * @param signType the value for PRODUCT_INFO.SIGN_TYPE
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    public void setSignType(String signType) {
        this.signType = signType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_INFO.PROPERTY_NAME
     *
     * @return the value of PRODUCT_INFO.PROPERTY_NAME
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    public String getPropertyName() {
        return propertyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_INFO.PROPERTY_NAME
     *
     * @param propertyName the value for PRODUCT_INFO.PROPERTY_NAME
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_INFO.UNIT
     *
     * @return the value of PRODUCT_INFO.UNIT
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_INFO.UNIT
     *
     * @param unit the value for PRODUCT_INFO.UNIT
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_INFO.MIN_COUNT
     *
     * @return the value of PRODUCT_INFO.MIN_COUNT
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    public String getMinCount() {
        return minCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_INFO.MIN_COUNT
     *
     * @param minCount the value for PRODUCT_INFO.MIN_COUNT
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    public void setMinCount(String minCount) {
        this.minCount = minCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_INFO.URL
     *
     * @return the value of PRODUCT_INFO.URL
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_INFO.URL
     *
     * @param url the value for PRODUCT_INFO.URL
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_INFO.DESCRIPTION
     *
     * @return the value of PRODUCT_INFO.DESCRIPTION
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_INFO.DESCRIPTION
     *
     * @param description the value for PRODUCT_INFO.DESCRIPTION
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_INFO.CREATE_TIME
     *
     * @return the value of PRODUCT_INFO.CREATE_TIME
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_INFO.CREATE_TIME
     *
     * @param createTime the value for PRODUCT_INFO.CREATE_TIME
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_INFO.UPDATE_TIME
     *
     * @return the value of PRODUCT_INFO.UPDATE_TIME
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_INFO.UPDATE_TIME
     *
     * @param updateTime the value for PRODUCT_INFO.UPDATE_TIME
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_INFO.STATUS
     *
     * @return the value of PRODUCT_INFO.STATUS
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_INFO.STATUS
     *
     * @param status the value for PRODUCT_INFO.STATUS
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_INFO
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ProductInfo other = (ProductInfo) that;
        return (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()))
            && (this.getMerchantId() == null ? other.getMerchantId() == null : this.getMerchantId().equals(other.getMerchantId()))
            && (this.getAppId() == null ? other.getAppId() == null : this.getAppId().equals(other.getAppId()))
            && (this.getProductDesc() == null ? other.getProductDesc() == null : this.getProductDesc().equals(other.getProductDesc()))
            && (this.getPropertyType() == null ? other.getPropertyType() == null : this.getPropertyType().equals(other.getPropertyType()))
            && (this.getPropertyCode() == null ? other.getPropertyCode() == null : this.getPropertyCode().equals(other.getPropertyCode()))
            && (this.getOriginOpenid() == null ? other.getOriginOpenid() == null : this.getOriginOpenid().equals(other.getOriginOpenid()))
            && (this.getSignType() == null ? other.getSignType() == null : this.getSignType().equals(other.getSignType()))
            && (this.getPropertyName() == null ? other.getPropertyName() == null : this.getPropertyName().equals(other.getPropertyName()))
            && (this.getUnit() == null ? other.getUnit() == null : this.getUnit().equals(other.getUnit()))
            && (this.getMinCount() == null ? other.getMinCount() == null : this.getMinCount().equals(other.getMinCount()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_INFO
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getMerchantId() == null) ? 0 : getMerchantId().hashCode());
        result = prime * result + ((getAppId() == null) ? 0 : getAppId().hashCode());
        result = prime * result + ((getProductDesc() == null) ? 0 : getProductDesc().hashCode());
        result = prime * result + ((getPropertyType() == null) ? 0 : getPropertyType().hashCode());
        result = prime * result + ((getPropertyCode() == null) ? 0 : getPropertyCode().hashCode());
        result = prime * result + ((getOriginOpenid() == null) ? 0 : getOriginOpenid().hashCode());
        result = prime * result + ((getSignType() == null) ? 0 : getSignType().hashCode());
        result = prime * result + ((getPropertyName() == null) ? 0 : getPropertyName().hashCode());
        result = prime * result + ((getUnit() == null) ? 0 : getUnit().hashCode());
        result = prime * result + ((getMinCount() == null) ? 0 : getMinCount().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_INFO
     *
     * @mbggenerated Thu Feb 23 16:37:02 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", merchantId=").append(merchantId);
        sb.append(", appId=").append(appId);
        sb.append(", productDesc=").append(productDesc);
        sb.append(", propertyType=").append(propertyType);
        sb.append(", propertyCode=").append(propertyCode);
        sb.append(", originOpenid=").append(originOpenid);
        sb.append(", signType=").append(signType);
        sb.append(", propertyName=").append(propertyName);
        sb.append(", unit=").append(unit);
        sb.append(", minCount=").append(minCount);
        sb.append(", url=").append(url);
        sb.append(", description=").append(description);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", status=").append(status);
        sb.append("]");
        return sb.toString();
    }
}