package com.fr.chain.property.db.entity;

public class PropertyKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROPERTY.PROPERTY_ID
     *
     * @mbggenerated Wed Feb 22 18:19:32 CST 2017
     */
    private String propertyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROPERTY.PROPERTY_ID
     *
     * @return the value of PROPERTY.PROPERTY_ID
     *
     * @mbggenerated Wed Feb 22 18:19:32 CST 2017
     */
    public String getPropertyId() {
        return propertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROPERTY.PROPERTY_ID
     *
     * @param propertyId the value for PROPERTY.PROPERTY_ID
     *
     * @mbggenerated Wed Feb 22 18:19:32 CST 2017
     */
    public void setPropertyId(String propertyId) {
        this.propertyId = propertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROPERTY
     *
     * @mbggenerated Wed Feb 22 18:19:32 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PropertyKey other = (PropertyKey) that;
        return (this.getPropertyId() == null ? other.getPropertyId() == null : this.getPropertyId().equals(other.getPropertyId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROPERTY
     *
     * @mbggenerated Wed Feb 22 18:19:32 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPropertyId() == null) ? 0 : getPropertyId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROPERTY
     *
     * @mbggenerated Wed Feb 22 18:19:32 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", propertyId=").append(propertyId);
        sb.append("]");
        return sb.toString();
    }
}