package com.fr.chain.ewallet.db.entity;

import com.fr.chain.utils.CustomDateSerializer;
import com.fr.chain.web.bean.Tab;
import java.util.Date;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="WALLET_ADDRESS")
public class WalletAdress extends WalletAdressKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WALLET_ADDRESS.MERCHANT_ID
     *
     * @mbggenerated Wed Feb 08 16:39:01 CST 2017
     */
    private String merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WALLET_ADDRESS.APP_ID
     *
     * @mbggenerated Wed Feb 08 16:39:01 CST 2017
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WALLET_ADDRESS.OPEN_ID
     *
     * @mbggenerated Wed Feb 08 16:39:01 CST 2017
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WALLET_ADDRESS.PRODUCT_ID
     *
     * @mbggenerated Wed Feb 08 16:39:01 CST 2017
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WALLET_ADDRESS.WALLET_CODE
     *
     * @mbggenerated Wed Feb 08 16:39:01 CST 2017
     */
    private String walletCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WALLET_ADDRESS.WALLET_ADDRESS
     *
     * @mbggenerated Wed Feb 08 16:39:01 CST 2017
     */
    private String walletAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WALLET_ADDRESS.CREATE_TIME
     *
     * @mbggenerated Wed Feb 08 16:39:01 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WALLET_ADDRESS.MERCHANT_ID
     *
     * @return the value of WALLET_ADDRESS.MERCHANT_ID
     *
     * @mbggenerated Wed Feb 08 16:39:01 CST 2017
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WALLET_ADDRESS.MERCHANT_ID
     *
     * @param merchantId the value for WALLET_ADDRESS.MERCHANT_ID
     *
     * @mbggenerated Wed Feb 08 16:39:01 CST 2017
     */
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WALLET_ADDRESS.APP_ID
     *
     * @return the value of WALLET_ADDRESS.APP_ID
     *
     * @mbggenerated Wed Feb 08 16:39:01 CST 2017
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WALLET_ADDRESS.APP_ID
     *
     * @param appId the value for WALLET_ADDRESS.APP_ID
     *
     * @mbggenerated Wed Feb 08 16:39:01 CST 2017
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WALLET_ADDRESS.OPEN_ID
     *
     * @return the value of WALLET_ADDRESS.OPEN_ID
     *
     * @mbggenerated Wed Feb 08 16:39:01 CST 2017
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WALLET_ADDRESS.OPEN_ID
     *
     * @param openId the value for WALLET_ADDRESS.OPEN_ID
     *
     * @mbggenerated Wed Feb 08 16:39:01 CST 2017
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WALLET_ADDRESS.PRODUCT_ID
     *
     * @return the value of WALLET_ADDRESS.PRODUCT_ID
     *
     * @mbggenerated Wed Feb 08 16:39:01 CST 2017
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WALLET_ADDRESS.PRODUCT_ID
     *
     * @param productId the value for WALLET_ADDRESS.PRODUCT_ID
     *
     * @mbggenerated Wed Feb 08 16:39:01 CST 2017
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WALLET_ADDRESS.WALLET_CODE
     *
     * @return the value of WALLET_ADDRESS.WALLET_CODE
     *
     * @mbggenerated Wed Feb 08 16:39:01 CST 2017
     */
    public String getWalletCode() {
        return walletCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WALLET_ADDRESS.WALLET_CODE
     *
     * @param walletCode the value for WALLET_ADDRESS.WALLET_CODE
     *
     * @mbggenerated Wed Feb 08 16:39:01 CST 2017
     */
    public void setWalletCode(String walletCode) {
        this.walletCode = walletCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WALLET_ADDRESS.WALLET_ADDRESS
     *
     * @return the value of WALLET_ADDRESS.WALLET_ADDRESS
     *
     * @mbggenerated Wed Feb 08 16:39:01 CST 2017
     */
    public String getWalletAddress() {
        return walletAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WALLET_ADDRESS.WALLET_ADDRESS
     *
     * @param walletAddress the value for WALLET_ADDRESS.WALLET_ADDRESS
     *
     * @mbggenerated Wed Feb 08 16:39:01 CST 2017
     */
    public void setWalletAddress(String walletAddress) {
        this.walletAddress = walletAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WALLET_ADDRESS.CREATE_TIME
     *
     * @return the value of WALLET_ADDRESS.CREATE_TIME
     *
     * @mbggenerated Wed Feb 08 16:39:01 CST 2017
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WALLET_ADDRESS.CREATE_TIME
     *
     * @param createTime the value for WALLET_ADDRESS.CREATE_TIME
     *
     * @mbggenerated Wed Feb 08 16:39:01 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WALLET_ADDRESS
     *
     * @mbggenerated Wed Feb 08 16:39:02 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WalletAdress other = (WalletAdress) that;
        return (this.getWalletId() == null ? other.getWalletId() == null : this.getWalletId().equals(other.getWalletId()))
            && (this.getMerchantId() == null ? other.getMerchantId() == null : this.getMerchantId().equals(other.getMerchantId()))
            && (this.getAppId() == null ? other.getAppId() == null : this.getAppId().equals(other.getAppId()))
            && (this.getOpenId() == null ? other.getOpenId() == null : this.getOpenId().equals(other.getOpenId()))
            && (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()))
            && (this.getWalletCode() == null ? other.getWalletCode() == null : this.getWalletCode().equals(other.getWalletCode()))
            && (this.getWalletAddress() == null ? other.getWalletAddress() == null : this.getWalletAddress().equals(other.getWalletAddress()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WALLET_ADDRESS
     *
     * @mbggenerated Wed Feb 08 16:39:02 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getWalletId() == null) ? 0 : getWalletId().hashCode());
        result = prime * result + ((getMerchantId() == null) ? 0 : getMerchantId().hashCode());
        result = prime * result + ((getAppId() == null) ? 0 : getAppId().hashCode());
        result = prime * result + ((getOpenId() == null) ? 0 : getOpenId().hashCode());
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getWalletCode() == null) ? 0 : getWalletCode().hashCode());
        result = prime * result + ((getWalletAddress() == null) ? 0 : getWalletAddress().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WALLET_ADDRESS
     *
     * @mbggenerated Wed Feb 08 16:39:02 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", merchantId=").append(merchantId);
        sb.append(", appId=").append(appId);
        sb.append(", openId=").append(openId);
        sb.append(", productId=").append(productId);
        sb.append(", walletCode=").append(walletCode);
        sb.append(", walletAddress=").append(walletAddress);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }
}