package com.fr.chain.chaintrade.db.entity;

import com.fr.chain.utils.CustomDateSerializer;
import com.fr.chain.web.bean.Tab;
import java.math.BigDecimal;
import java.util.Date;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="CHAIN_TRADE")
public class ChainTrade extends ChainTradeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAIN_TRADE.MERCHANT_ID
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    private String merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAIN_TRADE.APP_ID
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAIN_TRADE.OPEN_ID
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAIN_TRADE.ORDER_ID
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAIN_TRADE.TXID
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    private String txid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAIN_TRADE.CHAIN_CODE
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    private Integer chainCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAIN_TRADE.PRODUCT_ID
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAIN_TRADE.IS_DIGIT
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    private String isDigit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAIN_TRADE.UNIT
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAIN_TRADE.MINCOUNT
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    private String mincount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAIN_TRADE.COUNT
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    private String count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAIN_TRADE.AMOUNT
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAIN_TRADE.CREATE_TIME
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAIN_TRADE.UPDATE_TIME
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAIN_TRADE.PROCESS_STATUS
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    private Integer processStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHAIN_TRADE.MERCHANT_ID
     *
     * @return the value of CHAIN_TRADE.MERCHANT_ID
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHAIN_TRADE.MERCHANT_ID
     *
     * @param merchantId the value for CHAIN_TRADE.MERCHANT_ID
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHAIN_TRADE.APP_ID
     *
     * @return the value of CHAIN_TRADE.APP_ID
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHAIN_TRADE.APP_ID
     *
     * @param appId the value for CHAIN_TRADE.APP_ID
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHAIN_TRADE.OPEN_ID
     *
     * @return the value of CHAIN_TRADE.OPEN_ID
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHAIN_TRADE.OPEN_ID
     *
     * @param openId the value for CHAIN_TRADE.OPEN_ID
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHAIN_TRADE.ORDER_ID
     *
     * @return the value of CHAIN_TRADE.ORDER_ID
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHAIN_TRADE.ORDER_ID
     *
     * @param orderId the value for CHAIN_TRADE.ORDER_ID
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHAIN_TRADE.TXID
     *
     * @return the value of CHAIN_TRADE.TXID
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    public String getTxid() {
        return txid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHAIN_TRADE.TXID
     *
     * @param txid the value for CHAIN_TRADE.TXID
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    public void setTxid(String txid) {
        this.txid = txid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHAIN_TRADE.CHAIN_CODE
     *
     * @return the value of CHAIN_TRADE.CHAIN_CODE
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    public Integer getChainCode() {
        return chainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHAIN_TRADE.CHAIN_CODE
     *
     * @param chainCode the value for CHAIN_TRADE.CHAIN_CODE
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    public void setChainCode(Integer chainCode) {
        this.chainCode = chainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHAIN_TRADE.PRODUCT_ID
     *
     * @return the value of CHAIN_TRADE.PRODUCT_ID
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHAIN_TRADE.PRODUCT_ID
     *
     * @param productId the value for CHAIN_TRADE.PRODUCT_ID
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHAIN_TRADE.IS_DIGIT
     *
     * @return the value of CHAIN_TRADE.IS_DIGIT
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    public String getIsDigit() {
        return isDigit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHAIN_TRADE.IS_DIGIT
     *
     * @param isDigit the value for CHAIN_TRADE.IS_DIGIT
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    public void setIsDigit(String isDigit) {
        this.isDigit = isDigit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHAIN_TRADE.UNIT
     *
     * @return the value of CHAIN_TRADE.UNIT
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHAIN_TRADE.UNIT
     *
     * @param unit the value for CHAIN_TRADE.UNIT
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHAIN_TRADE.MINCOUNT
     *
     * @return the value of CHAIN_TRADE.MINCOUNT
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    public String getMincount() {
        return mincount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHAIN_TRADE.MINCOUNT
     *
     * @param mincount the value for CHAIN_TRADE.MINCOUNT
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    public void setMincount(String mincount) {
        this.mincount = mincount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHAIN_TRADE.COUNT
     *
     * @return the value of CHAIN_TRADE.COUNT
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    public String getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHAIN_TRADE.COUNT
     *
     * @param count the value for CHAIN_TRADE.COUNT
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    public void setCount(String count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHAIN_TRADE.AMOUNT
     *
     * @return the value of CHAIN_TRADE.AMOUNT
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHAIN_TRADE.AMOUNT
     *
     * @param amount the value for CHAIN_TRADE.AMOUNT
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHAIN_TRADE.CREATE_TIME
     *
     * @return the value of CHAIN_TRADE.CREATE_TIME
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHAIN_TRADE.CREATE_TIME
     *
     * @param createTime the value for CHAIN_TRADE.CREATE_TIME
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHAIN_TRADE.UPDATE_TIME
     *
     * @return the value of CHAIN_TRADE.UPDATE_TIME
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHAIN_TRADE.UPDATE_TIME
     *
     * @param updateTime the value for CHAIN_TRADE.UPDATE_TIME
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHAIN_TRADE.PROCESS_STATUS
     *
     * @return the value of CHAIN_TRADE.PROCESS_STATUS
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    public Integer getProcessStatus() {
        return processStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHAIN_TRADE.PROCESS_STATUS
     *
     * @param processStatus the value for CHAIN_TRADE.PROCESS_STATUS
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    public void setProcessStatus(Integer processStatus) {
        this.processStatus = processStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHAIN_TRADE
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ChainTrade other = (ChainTrade) that;
        return (this.getChainTradeId() == null ? other.getChainTradeId() == null : this.getChainTradeId().equals(other.getChainTradeId()))
            && (this.getMerchantId() == null ? other.getMerchantId() == null : this.getMerchantId().equals(other.getMerchantId()))
            && (this.getAppId() == null ? other.getAppId() == null : this.getAppId().equals(other.getAppId()))
            && (this.getOpenId() == null ? other.getOpenId() == null : this.getOpenId().equals(other.getOpenId()))
            && (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getTxid() == null ? other.getTxid() == null : this.getTxid().equals(other.getTxid()))
            && (this.getChainCode() == null ? other.getChainCode() == null : this.getChainCode().equals(other.getChainCode()))
            && (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()))
            && (this.getIsDigit() == null ? other.getIsDigit() == null : this.getIsDigit().equals(other.getIsDigit()))
            && (this.getUnit() == null ? other.getUnit() == null : this.getUnit().equals(other.getUnit()))
            && (this.getMincount() == null ? other.getMincount() == null : this.getMincount().equals(other.getMincount()))
            && (this.getCount() == null ? other.getCount() == null : this.getCount().equals(other.getCount()))
            && (this.getAmount() == null ? other.getAmount() == null : this.getAmount().equals(other.getAmount()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getProcessStatus() == null ? other.getProcessStatus() == null : this.getProcessStatus().equals(other.getProcessStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHAIN_TRADE
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getChainTradeId() == null) ? 0 : getChainTradeId().hashCode());
        result = prime * result + ((getMerchantId() == null) ? 0 : getMerchantId().hashCode());
        result = prime * result + ((getAppId() == null) ? 0 : getAppId().hashCode());
        result = prime * result + ((getOpenId() == null) ? 0 : getOpenId().hashCode());
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getTxid() == null) ? 0 : getTxid().hashCode());
        result = prime * result + ((getChainCode() == null) ? 0 : getChainCode().hashCode());
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getIsDigit() == null) ? 0 : getIsDigit().hashCode());
        result = prime * result + ((getUnit() == null) ? 0 : getUnit().hashCode());
        result = prime * result + ((getMincount() == null) ? 0 : getMincount().hashCode());
        result = prime * result + ((getCount() == null) ? 0 : getCount().hashCode());
        result = prime * result + ((getAmount() == null) ? 0 : getAmount().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getProcessStatus() == null) ? 0 : getProcessStatus().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHAIN_TRADE
     *
     * @mbggenerated Thu Feb 23 16:37:03 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", merchantId=").append(merchantId);
        sb.append(", appId=").append(appId);
        sb.append(", openId=").append(openId);
        sb.append(", orderId=").append(orderId);
        sb.append(", txid=").append(txid);
        sb.append(", chainCode=").append(chainCode);
        sb.append(", productId=").append(productId);
        sb.append(", isDigit=").append(isDigit);
        sb.append(", unit=").append(unit);
        sb.append(", mincount=").append(mincount);
        sb.append(", count=").append(count);
        sb.append(", amount=").append(amount);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", processStatus=").append(processStatus);
        sb.append("]");
        return sb.toString();
    }
}